# GitHub Actions workflow with PR comments
# Place this file at: .github/workflows/policy-check.yml

name: Repository Policy Check with PR Comment

on:
  pull_request:
    branches: [main]

jobs:
  policy-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install repo-policy
        run: |
          pip install repo-policy
      
      - name: Run policy check
        id: policy
        continue-on-error: true
        run: |
          repo-policy --keep-artifacts check
          echo "exit_code=$?" >> $GITHUB_OUTPUT
      
      - name: Comment PR with report
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const fs = require('fs');
            const reportPath = '.repo-policy-output/policy_report.md';
            let report;
            
            if (fs.existsSync(reportPath)) {
              report = fs.readFileSync(reportPath, 'utf8');
            } else {
              report = '# 🚨 Policy Check Failed\n\nPolicy check did not produce a report. Please check the workflow logs for errors.';
            }
            
            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('# Policy Check')
            );
            
            const commentBody = `${report}\n\n---\n*Updated at ${new Date().toISOString()}*`;
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody,
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody,
              });
            }
      
      - name: Upload policy reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: policy-reports
          path: .repo-policy-output/
      
      - name: Fail if policy check failed
        if: steps.policy.outcome == 'failure' || steps.policy.outputs.exit_code != '0'
        run: |
          echo "Policy check failed with exit code ${{ steps.policy.outputs.exit_code }}"
          exit 1
